Traceback (most recent call last):
  File "c:\users\lloyd\anaconda3\envs\dscore\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\lloyd\anaconda3\envs\dscore\lib\site-packages\nbclient\client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\lloyd\anaconda3\envs\dscore\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\lloyd\anaconda3\envs\dscore\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\lloyd\anaconda3\envs\dscore\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\lloyd\anaconda3\envs\dscore\lib\site-packages\nbclient\client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\lloyd\anaconda3\envs\dscore\lib\site-packages\nbclient\client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\lloyd\anaconda3\envs\dscore\lib\site-packages\nbclient\client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib inline
import time
from functools import partial

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import HTML
from matplotlib import animation
from scipy.integrate import solve_ivp
from tqdm import tqdm

from electrostatics import E, Timer, k_e

mpl.rc("figure", figsize=(10, 10))
mpl.rc("font", size=16)
mpl.rc("animation", embed_limit=40)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-1-cd31298c85f6>[0m in [0;36m<module>[1;34m[0m
[0;32m      9[0m [1;32mfrom[0m [0mmatplotlib[0m [1;32mimport[0m [0manimation[0m[1;33m[0m[1;33m[0m[0m
[0;32m     10[0m [1;32mfrom[0m [0mscipy[0m[1;33m.[0m[0mintegrate[0m [1;32mimport[0m [0msolve_ivp[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 11[1;33m [1;32mfrom[0m [0mtqdm[0m [1;32mimport[0m [0mtqdm[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     12[0m [1;33m[0m[0m
[0;32m     13[0m [1;32mfrom[0m [0melectrostatics[0m [1;32mimport[0m [0mE[0m[1;33m,[0m [0mTimer[0m[1;33m,[0m [0mk_e[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'tqdm'
ModuleNotFoundError: No module named 'tqdm'

